report_desc_mouse: make_report_desc_mouse.sh
	./make_report_desc_mouse.sh

mouse: report_desc_mouse
	cp report_desc_mouse /home/pi/report_desc_mouse
	sudo cp isticktoit_usb_mouse /usr/bin/isticktoit_usb

keyboard:
	sudo cp isticktoit_usb_keyboard /usr/bin/isticktoit_usb
