build:
	cargo build

run:
	sudo ./target/debug/botter ../data.txt true

totem:
	sudo nice -n -19 ./target/debug/botter ../scripts/library-totem true

limina:
	sudo nice -n -19 ./target/debug/botter ../scripts/limina2 true

rover:
	sudo nice -n -19 ./target/debug/botter ../scripts/rover.txt true

assassin:
	sudo nice -n -19 ./target/debug/botter ../scripts/assassin.txt true

outlaw:
	sudo nice -n -19 ./target/debug/botter ../scripts/outlaw.txt true
