build:
	cargo build

run:
	sudo ./target/debug/botter ../data.txt true

totem:
	sudo nice -n -19 ./target/debug/botter ../scripts/library-totem true

limina:
	sudo nice -n -19 ./target/debug/botter ../scripts/limina2 true
